//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "allowance_deduction_types")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub organization_id: i32,
    pub branch_id: Option<i32>,
    pub name: String,
    pub name_urdu: Option<String>,
    pub r#type: String,
    pub occurrence: String,
    pub frequency: Option<String>,
    pub is_taxable: bool,
    pub description: Option<String>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::branches::Entity",
        from = "Column::BranchId",
        to = "super::branches::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Branches,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Organizations,
    #[sea_orm(has_many = "super::salary_structure_components::Entity")]
    SalaryStructureComponents,
    #[sea_orm(has_many = "super::staff_monthly_salary_details::Entity")]
    StaffMonthlySalaryDetails,
    #[sea_orm(has_many = "super::staff_salary_allowances::Entity")]
    StaffSalaryAllowances,
}

impl Related<super::branches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Branches.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::salary_structure_components::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalaryStructureComponents.def()
    }
}

impl Related<super::staff_monthly_salary_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffMonthlySalaryDetails.def()
    }
}

impl Related<super::staff_salary_allowances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffSalaryAllowances.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
