//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "branch_class_levels")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub branch_id: i32,
    pub class_level_id: i32,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::branches::Entity",
        from = "Column::BranchId",
        to = "super::branches::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Branches,
    #[sea_orm(
        belongs_to = "super::class_levels::Entity",
        from = "Column::ClassLevelId",
        to = "super::class_levels::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    ClassLevels,
}

impl Related<super::branches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Branches.def()
    }
}

impl Related<super::class_levels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClassLevels.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
