//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cities")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub name_urdu: Option<String>,
    pub province_id: i32,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::addresses::Entity")]
    Addresses,
    #[sea_orm(has_many = "super::branches::Entity")]
    Branches,
    #[sea_orm(has_many = "super::organizations::Entity")]
    Organizations,
    #[sea_orm(
        belongs_to = "super::provinces::Entity",
        from = "Column::ProvinceId",
        to = "super::provinces::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Provinces,
}

impl Related<super::addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Addresses.def()
    }
}

impl Related<super::branches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Branches.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::provinces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Provinces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
