//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "classes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub master_class_id: i32,
    pub master_section_id: i32,
    pub academic_year_id: i32,
    pub class_teacher_id: Option<i32>,
    pub capacity: Option<i32>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::academic_years::Entity",
        from = "Column::AcademicYearId",
        to = "super::academic_years::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    AcademicYears,
    #[sea_orm(
        belongs_to = "super::master_classes::Entity",
        from = "Column::MasterClassId",
        to = "super::master_classes::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    MasterClasses,
    #[sea_orm(
        belongs_to = "super::master_sections::Entity",
        from = "Column::MasterSectionId",
        to = "super::master_sections::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    MasterSections,
    #[sea_orm(
        belongs_to = "super::teachers::Entity",
        from = "Column::ClassTeacherId",
        to = "super::teachers::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Teachers,
}

impl Related<super::academic_years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademicYears.def()
    }
}

impl Related<super::master_classes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MasterClasses.def()
    }
}

impl Related<super::master_sections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MasterSections.def()
    }
}

impl Related<super::teachers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teachers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
