//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "class_progressions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub from_class_id: i32,
    pub to_class_id: i32,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::master_classes::Entity",
        from = "Column::FromClassId",
        to = "super::master_classes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MasterClasses2,
    #[sea_orm(
        belongs_to = "super::master_classes::Entity",
        from = "Column::ToClassId",
        to = "super::master_classes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MasterClasses1,
}

impl ActiveModelBehavior for ActiveModel {}
