//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "exams")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub branch_id: i32,
    pub class_id: i32,
    pub academic_year_id: i32,
    pub exam_type_id: i32,
    pub name: String,
    pub name_urdu: Option<String>,
    pub start_date: Date,
    pub end_date: Date,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::academic_years::Entity",
        from = "Column::AcademicYearId",
        to = "super::academic_years::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    AcademicYears,
    #[sea_orm(
        belongs_to = "super::branches::Entity",
        from = "Column::BranchId",
        to = "super::branches::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Branches,
    #[sea_orm(
        belongs_to = "super::classes::Entity",
        from = "Column::ClassId",
        to = "super::classes::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Classes,
    #[sea_orm(has_many = "super::exam_subjects::Entity")]
    ExamSubjects,
    #[sea_orm(
        belongs_to = "super::exam_types::Entity",
        from = "Column::ExamTypeId",
        to = "super::exam_types::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    ExamTypes,
}

impl Related<super::academic_years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademicYears.def()
    }
}

impl Related<super::branches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Branches.def()
    }
}

impl Related<super::classes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Classes.def()
    }
}

impl Related<super::exam_subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExamSubjects.def()
    }
}

impl Related<super::exam_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExamTypes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
