//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "exam_subjects")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub exam_id: i32,
    pub subject_id: i32,
    pub total_marks: i32,
    pub passing_marks: i32,
    pub exam_date: Date,
    pub exam_time: Option<String>,
    pub venue: Option<String>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::exams::Entity",
        from = "Column::ExamId",
        to = "super::exams::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Exams,
    #[sea_orm(has_many = "super::results::Entity")]
    Results,
    #[sea_orm(
        belongs_to = "super::subjects::Entity",
        from = "Column::SubjectId",
        to = "super::subjects::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Subjects,
}

impl Related<super::exams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Exams.def()
    }
}

impl Related<super::results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Results.def()
    }
}

impl Related<super::subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subjects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
