//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "expenses")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub branch_id: i32,
    pub expense_category_id: i32,
    pub amount: i32,
    pub description: String,
    pub expense_date: Date,
    pub receipt_number: Option<String>,
    pub payment_method_id: i32,
    pub reference_number: Option<String>,
    pub approved_by: Option<i32>,
    pub entered_by: i32,
    pub remarks: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::branches::Entity",
        from = "Column::BranchId",
        to = "super::branches::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Branches,
    #[sea_orm(
        belongs_to = "super::expense_categories::Entity",
        from = "Column::ExpenseCategoryId",
        to = "super::expense_categories::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    ExpenseCategories,
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::PaymentMethodId",
        to = "super::payment_methods::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    PaymentMethods,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ApprovedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::EnteredBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Users1,
}

impl Related<super::branches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Branches.def()
    }
}

impl Related<super::expense_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExpenseCategories.def()
    }
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
