//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fee_types")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub organization_id: i32,
    pub name: String,
    pub name_urdu: Option<String>,
    pub recurrence: String,
    pub description: Option<String>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::fee_bills::Entity")]
    FeeBills,
    #[sea_orm(has_many = "super::fee_structures::Entity")]
    FeeStructures,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Organizations,
    #[sea_orm(has_many = "super::scholarships::Entity")]
    Scholarships,
    #[sea_orm(has_many = "super::student_discounts::Entity")]
    StudentDiscounts,
}

impl Related<super::fee_bills::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeBills.def()
    }
}

impl Related<super::fee_structures::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeStructures.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::scholarships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Scholarships.def()
    }
}

impl Related<super::student_discounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudentDiscounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
