//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fee_structures")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub organization_id: i32,
    pub branch_id: Option<i32>,
    pub class_level_id: Option<i32>,
    pub master_class_id: Option<i32>,
    pub student_id: Option<i32>,
    pub fee_type_id: i32,
    pub academic_year_id: i32,
    pub amount: i32,
    pub due_day: i32,
    pub bill_generation_frequency: String,
    pub late_fee_type: Option<String>,
    pub late_fee_value: Option<i32>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::academic_years::Entity",
        from = "Column::AcademicYearId",
        to = "super::academic_years::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    AcademicYears,
    #[sea_orm(
        belongs_to = "super::branches::Entity",
        from = "Column::BranchId",
        to = "super::branches::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Branches,
    #[sea_orm(
        belongs_to = "super::class_levels::Entity",
        from = "Column::ClassLevelId",
        to = "super::class_levels::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    ClassLevels,
    #[sea_orm(
        belongs_to = "super::fee_types::Entity",
        from = "Column::FeeTypeId",
        to = "super::fee_types::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    FeeTypes,
    #[sea_orm(
        belongs_to = "super::master_classes::Entity",
        from = "Column::MasterClassId",
        to = "super::master_classes::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    MasterClasses,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::students::Entity",
        from = "Column::StudentId",
        to = "super::students::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Students,
}

impl Related<super::academic_years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademicYears.def()
    }
}

impl Related<super::branches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Branches.def()
    }
}

impl Related<super::class_levels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClassLevels.def()
    }
}

impl Related<super::fee_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeTypes.def()
    }
}

impl Related<super::master_classes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MasterClasses.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::students::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Students.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
