//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fee_payments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub fee_bill_id: i32,
    pub student_id: i32,
    pub payment_method_id: i32,
    pub amount_paid: i32,
    pub reference_number: Option<String>,
    pub payment_date: Date,
    #[sea_orm(unique)]
    pub receipt_number: String,
    pub remarks: Option<String>,
    pub received_by: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::fee_bills::Entity",
        from = "Column::FeeBillId",
        to = "super::fee_bills::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    FeeBills,
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::PaymentMethodId",
        to = "super::payment_methods::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    PaymentMethods,
    #[sea_orm(
        belongs_to = "super::students::Entity",
        from = "Column::StudentId",
        to = "super::students::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Students,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ReceivedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Users,
}

impl Related<super::fee_bills::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeBills.def()
    }
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl Related<super::students::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Students.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
