//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod academic_years;
pub mod addresses;
pub mod audit_logs;
pub mod branch_contacts;
pub mod branches;
pub mod cities;
pub mod class_progressions;
pub mod classes;
pub mod contacts;
pub mod guardians;
pub mod master_classes;
pub mod master_sections;
pub mod organization_settings;
pub mod organizations;
pub mod permissions;
pub mod provinces;
pub mod qualifications;
pub mod role_permissions;
pub mod roles;
pub mod staff;
pub mod staff_types;
pub mod streams;
pub mod student_guardians;
pub mod students;
pub mod transfers;
pub mod user_roles;
pub mod users;
