//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod academic_years;
pub mod class_progressions;
pub mod classes;
pub mod master_classes;
pub mod master_sections;
pub mod permissions;
pub mod role_permissions;
pub mod roles;
pub mod streams;
pub mod students;
pub mod teachers;
pub mod user_roles;
pub mod users;
