//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "organizations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub name_urdu: Option<String>,
    pub logo_url: Option<String>,
    pub website: Option<String>,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub city_id: Option<i32>,
    pub address: Option<String>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::academic_years::Entity")]
    AcademicYears,
    #[sea_orm(has_many = "super::allowance_deduction_types::Entity")]
    AllowanceDeductionTypes,
    #[sea_orm(has_many = "super::audit_logs::Entity")]
    AuditLogs,
    #[sea_orm(has_many = "super::branches::Entity")]
    Branches,
    #[sea_orm(
        belongs_to = "super::cities::Entity",
        from = "Column::CityId",
        to = "super::cities::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Cities,
    #[sea_orm(has_many = "super::class_levels::Entity")]
    ClassLevels,
    #[sea_orm(has_many = "super::discounts::Entity")]
    Discounts,
    #[sea_orm(has_many = "super::exam_types::Entity")]
    ExamTypes,
    #[sea_orm(has_many = "super::expense_categories::Entity")]
    ExpenseCategories,
    #[sea_orm(has_many = "super::fee_structures::Entity")]
    FeeStructures,
    #[sea_orm(has_many = "super::fee_types::Entity")]
    FeeTypes,
    #[sea_orm(has_many = "super::leave_types::Entity")]
    LeaveTypes,
    #[sea_orm(has_many = "super::master_classes::Entity")]
    MasterClasses,
    #[sea_orm(has_many = "super::master_sections::Entity")]
    MasterSections,
    #[sea_orm(has_many = "super::organization_settings::Entity")]
    OrganizationSettings,
    #[sea_orm(has_many = "super::payment_methods::Entity")]
    PaymentMethods,
    #[sea_orm(has_many = "super::permissions::Entity")]
    Permissions,
    #[sea_orm(has_many = "super::roles::Entity")]
    Roles,
    #[sea_orm(has_many = "super::salary_structures::Entity")]
    SalaryStructures,
    #[sea_orm(has_many = "super::scholarships::Entity")]
    Scholarships,
    #[sea_orm(has_many = "super::staff::Entity")]
    Staff,
    #[sea_orm(has_many = "super::staff_types::Entity")]
    StaffTypes,
    #[sea_orm(has_many = "super::streams::Entity")]
    Streams,
    #[sea_orm(has_many = "super::students::Entity")]
    Students,
    #[sea_orm(has_many = "super::subjects::Entity")]
    Subjects,
    #[sea_orm(has_many = "super::user_roles::Entity")]
    UserRoles,
    #[sea_orm(has_many = "super::users::Entity")]
    Users,
}

impl Related<super::academic_years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademicYears.def()
    }
}

impl Related<super::allowance_deduction_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AllowanceDeductionTypes.def()
    }
}

impl Related<super::audit_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditLogs.def()
    }
}

impl Related<super::branches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Branches.def()
    }
}

impl Related<super::cities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cities.def()
    }
}

impl Related<super::class_levels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClassLevels.def()
    }
}

impl Related<super::discounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Discounts.def()
    }
}

impl Related<super::exam_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExamTypes.def()
    }
}

impl Related<super::expense_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExpenseCategories.def()
    }
}

impl Related<super::fee_structures::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeStructures.def()
    }
}

impl Related<super::fee_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeTypes.def()
    }
}

impl Related<super::leave_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LeaveTypes.def()
    }
}

impl Related<super::master_classes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MasterClasses.def()
    }
}

impl Related<super::master_sections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MasterSections.def()
    }
}

impl Related<super::organization_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationSettings.def()
    }
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl Related<super::permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Permissions.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl Related<super::salary_structures::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalaryStructures.def()
    }
}

impl Related<super::scholarships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Scholarships.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl Related<super::staff_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffTypes.def()
    }
}

impl Related<super::streams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Streams.def()
    }
}

impl Related<super::students::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Students.def()
    }
}

impl Related<super::subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subjects.def()
    }
}

impl Related<super::user_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoles.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
