//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "payment_methods")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub organization_id: i32,
    pub name: String,
    pub name_urdu: Option<String>,
    pub requires_reference: bool,
    pub description: Option<String>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::fee_payments::Entity")]
    FeePayments,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Organizations,
    #[sea_orm(has_many = "super::salary_payments::Entity")]
    SalaryPayments,
    #[sea_orm(has_many = "super::staff_monthly_salaries::Entity")]
    StaffMonthlySalaries,
}

impl Related<super::fee_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeePayments.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::salary_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalaryPayments.def()
    }
}

impl Related<super::staff_monthly_salaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffMonthlySalaries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
