//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::academic_years::Entity as AcademicYears;
pub use super::class_progressions::Entity as ClassProgressions;
pub use super::classes::Entity as Classes;
pub use super::master_classes::Entity as MasterClasses;
pub use super::master_sections::Entity as MasterSections;
pub use super::streams::Entity as Streams;
pub use super::students::Entity as Students;
pub use super::teachers::Entity as Teachers;
pub use super::users::Entity as Users;
