//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "salary_increments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub staff_id: i32,
    pub staff_salary_id: i32,
    pub increment_type: String,
    pub previous_basic_salary: i32,
    pub new_basic_salary: i32,
    pub increment_amount: i32,
    pub effective_from: Date,
    pub reason: Option<String>,
    pub approved_by: i32,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::StaffId",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Staff,
    #[sea_orm(
        belongs_to = "super::staff_salaries::Entity",
        from = "Column::StaffSalaryId",
        to = "super::staff_salaries::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    StaffSalaries,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ApprovedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Users,
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl Related<super::staff_salaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffSalaries.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
