//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "salary_payments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub staff_monthly_salary_id: i32,
    pub staff_id: i32,
    pub amount_paid: i32,
    pub payment_method_id: i32,
    pub reference_number: Option<String>,
    pub payment_date: Date,
    #[sea_orm(unique)]
    pub receipt_number: String,
    pub remarks: Option<String>,
    pub paid_by: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::PaymentMethodId",
        to = "super::payment_methods::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    PaymentMethods,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::StaffId",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Staff,
    #[sea_orm(
        belongs_to = "super::staff_monthly_salaries::Entity",
        from = "Column::StaffMonthlySalaryId",
        to = "super::staff_monthly_salaries::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    StaffMonthlySalaries,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::PaidBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Users,
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl Related<super::staff_monthly_salaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffMonthlySalaries.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
