//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "staff_salary_allowances")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub staff_salary_id: i32,
    pub allowance_deduction_type_id: i32,
    pub amount: i32,
    pub calculation_type: String,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::allowance_deduction_types::Entity",
        from = "Column::AllowanceDeductionTypeId",
        to = "super::allowance_deduction_types::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    AllowanceDeductionTypes,
    #[sea_orm(
        belongs_to = "super::staff_salaries::Entity",
        from = "Column::StaffSalaryId",
        to = "super::staff_salaries::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    StaffSalaries,
}

impl Related<super::allowance_deduction_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AllowanceDeductionTypes.def()
    }
}

impl Related<super::staff_salaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffSalaries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
