//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "staff_monthly_salaries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub staff_id: i32,
    pub branch_id: i32,
    pub academic_year_id: i32,
    pub salary_month: i32,
    pub salary_year: i32,
    pub working_days: i32,
    pub present_days: i32,
    pub absent_days: i32,
    pub gross_salary: i32,
    pub total_deductions: i32,
    pub net_salary: i32,
    pub status: String,
    pub approved_by: Option<i32>,
    pub approved_at: Option<DateTimeWithTimeZone>,
    pub payment_date: Option<Date>,
    pub payment_method_id: Option<i32>,
    pub remarks: Option<String>,
    pub generated_by: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::academic_years::Entity",
        from = "Column::AcademicYearId",
        to = "super::academic_years::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    AcademicYears,
    #[sea_orm(
        belongs_to = "super::branches::Entity",
        from = "Column::BranchId",
        to = "super::branches::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Branches,
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::PaymentMethodId",
        to = "super::payment_methods::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    PaymentMethods,
    #[sea_orm(has_many = "super::salary_payments::Entity")]
    SalaryPayments,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::StaffId",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Staff,
    #[sea_orm(has_many = "super::staff_loan_deductions::Entity")]
    StaffLoanDeductions,
    #[sea_orm(has_many = "super::staff_monthly_salary_details::Entity")]
    StaffMonthlySalaryDetails,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ApprovedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::GeneratedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Users1,
}

impl Related<super::academic_years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademicYears.def()
    }
}

impl Related<super::branches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Branches.def()
    }
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl Related<super::salary_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalaryPayments.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl Related<super::staff_loan_deductions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffLoanDeductions.def()
    }
}

impl Related<super::staff_monthly_salary_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffMonthlySalaryDetails.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
