//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "staff_loan_deductions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub staff_loan_id: i32,
    pub staff_monthly_salary_id: i32,
    pub amount_deducted: i32,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::staff_loans::Entity",
        from = "Column::StaffLoanId",
        to = "super::staff_loans::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    StaffLoans,
    #[sea_orm(
        belongs_to = "super::staff_monthly_salaries::Entity",
        from = "Column::StaffMonthlySalaryId",
        to = "super::staff_monthly_salaries::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    StaffMonthlySalaries,
}

impl Related<super::staff_loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffLoans.def()
    }
}

impl Related<super::staff_monthly_salaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffMonthlySalaries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
