//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "staff")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub organization_id: i32,
    pub branch_id: Option<i32>,
    pub staff_type_id: i32,
    pub first_name: String,
    pub last_name: String,
    pub father_name: Option<String>,
    pub date_of_birth: Date,
    pub gender: String,
    pub cnic: Option<String>,
    pub joining_date: Date,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::branches::Entity",
        from = "Column::BranchId",
        to = "super::branches::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Branches,
    #[sea_orm(has_many = "super::class_subjects::Entity")]
    ClassSubjects,
    #[sea_orm(has_many = "super::classes::Entity")]
    Classes,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Organizations,
    #[sea_orm(has_many = "super::qualifications::Entity")]
    Qualifications,
    #[sea_orm(has_many = "super::salary_increments::Entity")]
    SalaryIncrements,
    #[sea_orm(has_many = "super::salary_payments::Entity")]
    SalaryPayments,
    #[sea_orm(has_many = "super::staff_leaves::Entity")]
    StaffLeaves,
    #[sea_orm(has_many = "super::staff_loans::Entity")]
    StaffLoans,
    #[sea_orm(has_many = "super::staff_monthly_salaries::Entity")]
    StaffMonthlySalaries,
    #[sea_orm(has_many = "super::staff_salaries::Entity")]
    StaffSalaries,
    #[sea_orm(
        belongs_to = "super::staff_types::Entity",
        from = "Column::StaffTypeId",
        to = "super::staff_types::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    StaffTypes,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Users,
}

impl Related<super::branches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Branches.def()
    }
}

impl Related<super::class_subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClassSubjects.def()
    }
}

impl Related<super::classes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Classes.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::qualifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Qualifications.def()
    }
}

impl Related<super::salary_increments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalaryIncrements.def()
    }
}

impl Related<super::salary_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalaryPayments.def()
    }
}

impl Related<super::staff_leaves::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffLeaves.def()
    }
}

impl Related<super::staff_loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffLoans.def()
    }
}

impl Related<super::staff_monthly_salaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffMonthlySalaries.def()
    }
}

impl Related<super::staff_salaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffSalaries.def()
    }
}

impl Related<super::staff_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffTypes.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
