//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "staff_salaries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub staff_id: i32,
    pub salary_structure_id: i32,
    pub basic_salary: i32,
    pub effective_from: Date,
    pub effective_to: Option<Date>,
    pub remarks: Option<String>,
    pub assigned_by: i32,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::salary_increments::Entity")]
    SalaryIncrements,
    #[sea_orm(
        belongs_to = "super::salary_structures::Entity",
        from = "Column::SalaryStructureId",
        to = "super::salary_structures::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    SalaryStructures,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::StaffId",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Staff,
    #[sea_orm(has_many = "super::staff_salary_allowances::Entity")]
    StaffSalaryAllowances,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::AssignedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Users,
}

impl Related<super::salary_increments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalaryIncrements.def()
    }
}

impl Related<super::salary_structures::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalaryStructures.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl Related<super::staff_salary_allowances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffSalaryAllowances.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
