//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "student_enrollments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub student_id: i32,
    pub class_id: i32,
    pub academic_year_id: i32,
    pub roll_number: Option<String>,
    pub enrollment_date: Date,
    pub status: String,
    pub remarks: Option<String>,
    pub enrolled_by: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::academic_years::Entity",
        from = "Column::AcademicYearId",
        to = "super::academic_years::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    AcademicYears,
    #[sea_orm(
        belongs_to = "super::classes::Entity",
        from = "Column::ClassId",
        to = "super::classes::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Classes,
    #[sea_orm(
        belongs_to = "super::students::Entity",
        from = "Column::StudentId",
        to = "super::students::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Students,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::EnrolledBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Users,
}

impl Related<super::academic_years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademicYears.def()
    }
}

impl Related<super::classes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Classes.def()
    }
}

impl Related<super::students::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Students.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
