//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "students")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub organization_id: i32,
    pub branch_id: i32,
    pub first_name: String,
    pub last_name: String,
    pub date_of_birth: Date,
    pub gender: String,
    pub roll_number: String,
    pub admission_date: Date,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attendance::Entity")]
    Attendance,
    #[sea_orm(
        belongs_to = "super::branches::Entity",
        from = "Column::BranchId",
        to = "super::branches::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Branches,
    #[sea_orm(has_many = "super::fee_arrears::Entity")]
    FeeArrears,
    #[sea_orm(has_many = "super::fee_bills::Entity")]
    FeeBills,
    #[sea_orm(has_many = "super::fee_payments::Entity")]
    FeePayments,
    #[sea_orm(has_many = "super::fee_structures::Entity")]
    FeeStructures,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Organizations,
    #[sea_orm(has_many = "super::results::Entity")]
    Results,
    #[sea_orm(has_many = "super::student_discounts::Entity")]
    StudentDiscounts,
    #[sea_orm(has_many = "super::student_enrollments::Entity")]
    StudentEnrollments,
    #[sea_orm(has_many = "super::student_guardians::Entity")]
    StudentGuardians,
    #[sea_orm(has_many = "super::student_scholarships::Entity")]
    StudentScholarships,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Users,
}

impl Related<super::attendance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attendance.def()
    }
}

impl Related<super::branches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Branches.def()
    }
}

impl Related<super::fee_arrears::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeArrears.def()
    }
}

impl Related<super::fee_bills::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeBills.def()
    }
}

impl Related<super::fee_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeePayments.def()
    }
}

impl Related<super::fee_structures::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeStructures.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Results.def()
    }
}

impl Related<super::student_discounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudentDiscounts.def()
    }
}

impl Related<super::student_enrollments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudentEnrollments.def()
    }
}

impl Related<super::student_guardians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudentGuardians.def()
    }
}

impl Related<super::student_scholarships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudentScholarships.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
