//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "student_guardians")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub student_id: i32,
    pub guardian_id: i32,
    pub is_primary_contact: bool,
    pub is_emergency_contact: bool,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::guardians::Entity",
        from = "Column::GuardianId",
        to = "super::guardians::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Guardians,
    #[sea_orm(
        belongs_to = "super::students::Entity",
        from = "Column::StudentId",
        to = "super::students::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Students,
}

impl Related<super::guardians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Guardians.def()
    }
}

impl Related<super::students::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Students.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
