//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub organization_id: Option<i32>,
    pub branch_id: Option<i32>,
    #[sea_orm(unique)]
    pub username: String,
    #[sea_orm(unique)]
    pub email: String,
    pub password_hash: String,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attendance::Entity")]
    Attendance,
    #[sea_orm(has_many = "super::audit_logs::Entity")]
    AuditLogs,
    #[sea_orm(
        belongs_to = "super::branches::Entity",
        from = "Column::BranchId",
        to = "super::branches::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Branches,
    #[sea_orm(has_many = "super::fee_arrears::Entity")]
    FeeArrears,
    #[sea_orm(has_many = "super::fee_payments::Entity")]
    FeePayments,
    #[sea_orm(has_many = "super::guardians::Entity")]
    Guardians,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Organizations,
    #[sea_orm(has_many = "super::results::Entity")]
    Results,
    #[sea_orm(has_many = "super::salary_increments::Entity")]
    SalaryIncrements,
    #[sea_orm(has_many = "super::salary_payments::Entity")]
    SalaryPayments,
    #[sea_orm(has_many = "super::staff::Entity")]
    Staff,
    #[sea_orm(has_many = "super::staff_leaves::Entity")]
    StaffLeaves,
    #[sea_orm(has_many = "super::staff_loans::Entity")]
    StaffLoans,
    #[sea_orm(has_many = "super::staff_salaries::Entity")]
    StaffSalaries,
    #[sea_orm(has_many = "super::student_enrollments::Entity")]
    StudentEnrollments,
    #[sea_orm(has_many = "super::students::Entity")]
    Students,
    #[sea_orm(has_many = "super::user_roles::Entity")]
    UserRoles,
}

impl Related<super::attendance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attendance.def()
    }
}

impl Related<super::audit_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditLogs.def()
    }
}

impl Related<super::branches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Branches.def()
    }
}

impl Related<super::fee_arrears::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeArrears.def()
    }
}

impl Related<super::fee_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeePayments.def()
    }
}

impl Related<super::guardians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Guardians.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Results.def()
    }
}

impl Related<super::salary_increments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalaryIncrements.def()
    }
}

impl Related<super::salary_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalaryPayments.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl Related<super::staff_leaves::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffLeaves.def()
    }
}

impl Related<super::staff_loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffLoans.def()
    }
}

impl Related<super::staff_salaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffSalaries.def()
    }
}

impl Related<super::student_enrollments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudentEnrollments.def()
    }
}

impl Related<super::students::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Students.def()
    }
}

impl Related<super::user_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
